import {IParticleEffectPresetRegistry} from "./types";

export const DEFAULT_PARTICLE_EFFECT_AREA_WIDTH = 960;
export const FIREWORK_SALUTE_COLORS = [
    0xff4a4a,
    0xffd166,
    0x62f2ff,
    0x8dff72,
    0xb78cff,
    0xffffff,
];

export const particleEffectPresets: IParticleEffectPresetRegistry = {
    snowfall: {
        emitters: [{
            emitArea: {x: 0, y: -80, width: DEFAULT_PARTICLE_EFFECT_AREA_WIDTH},
            reserve: 140,
            maxAliveParticles: 200,
            frequency: 110,
            quantity: 3,
            lifespan: {min: 5200, max: 7600},
            speedX: {min: -45, max: 45},
            speedY: {min: 70, max: 145},
            gravityY: 8,
            scale: {start: 0.52, end: 0.52},
            rotate: {min: 0, max: 540},
            alpha: {start: 0.92, end: 0.92},
        }],
    },
    cannonLeft: {
        emitters: [{
            emitArea: {x: 0, y: 0, width: 1},
            reserve: 90,
            maxAliveParticles: 140,
            frequency: -1,
            quantity: 56,
            lifespan: {min: 1700, max: 2600},
            angle: {min: 292, max: 338},
            speed: {min: 360, max: 720},
            speedX: {min: 0, max: 0},
            speedY: {min: 0, max: 0},
            gravityY: 520,
            scale: {start: 0.58, end: 0.18},
            rotate: {min: 0, max: 900},
            alpha: {start: 1, end: 0},
        }],
    },
    cannonRight: {
        emitters: [{
            emitArea: {x: 0, y: 0, width: 1},
            reserve: 90,
            maxAliveParticles: 140,
            frequency: -1,
            quantity: 56,
            lifespan: {min: 1700, max: 2600},
            angle: {min: 202, max: 248},
            speed: {min: 360, max: 720},
            speedX: {min: 0, max: 0},
            speedY: {min: 0, max: 0},
            gravityY: 520,
            scale: {start: 0.58, end: 0.18},
            rotate: {min: 0, max: 900},
            alpha: {start: 1, end: 0},
        }],
    },
    fireworksBurst: {
        emitters: [{
            emitArea: {x: 0, y: 0, width: 1},
            reserve: 120,
            maxAliveParticles: 180,
            frequency: -1,
            quantity: 72,
            lifespan: {min: 1200, max: 2100},
            angle: {min: 0, max: 360},
            speed: {min: 220, max: 620},
            speedX: {min: 0, max: 0},
            speedY: {min: 0, max: 0},
            gravityY: 280,
            scale: {start: 0.52, end: 0.08},
            rotate: {min: 0, max: 1080},
            alpha: {start: 1, end: 0},
        }],
    },
    /** Root-частица салюта: одна "ракета" летит снизу вверх и в момент смерти запускает burst-actions. */
    fireworkRocket: {
        emitters: [{
            emitArea: {x: 80, y: 0, width: DEFAULT_PARTICLE_EFFECT_AREA_WIDTH - 160},
            reserve: 10,
            maxAliveParticles: 18,
            frequency: 620,
            quantity: 1,
            lifespan: {min: 980, max: 1450},
            angle: {min: 254, max: 286},
            speed: {min: 520, max: 760},
            speedX: {min: 0, max: 0},
            speedY: {min: 0, max: 0},
            gravityY: 250,
            scale: {start: 0.34, end: 0.14},
            rotate: {min: -12, max: 12},
            alpha: {start: 1, end: 0.54},
            tint: FIREWORK_SALUTE_COLORS,
        }],
    },
    /** Follow-частицы хвоста: отдельный emitter следует за ракетой и создает короткий затухающий шлейф. */
    fireworkRocketTrail: {
        emitters: [{
            emitArea: {x: 0, y: 0, width: 1},
            reserve: 24,
            maxAliveParticles: 12,
            frequency: 28,
            quantity: 1,
            lifespan: {min: 300, max: 600},
            speedX: {min: -24, max: 24},
            speedY: {min: -8, max: 42},
            gravityY: 70,
            scale: {start: 0.22, end: 0.03},
            rotate: {min: -33, max: 33},
            alpha: {start: 0.62, end: 0},
            tint: FIREWORK_SALUTE_COLORS,
        }],
    },
    /** Плотный burst: много мелких быстрых частиц для яркого основного взрыва. */
    protonFireworksDenseBurst: {
        emitters: [{
            emitArea: {x: 0, y: 0, width: 1},
            reserve: 300,
            maxAliveParticles: 360,
            frequency: -1,
            quantity: 260,
            lifespan: {min: 1000, max: 2800},
            angle: {min: 0, max: 360},
            speed: {min: 170, max: 460},
            speedX: {min: 0, max: 0},
            speedY: {min: 0, max: 0},
            gravityY: 330,
            scale: {start: 0.2, end: 0.035},
            rotate: {min: -33, max: 33},
            alpha: {start: 1, end: 0},
            tint: FIREWORK_SALUTE_COLORS,
        }],
    },
    /** Мягкий burst: меньше крупных и медленных частиц для редкого альтернативного взрыва. */
    protonFireworksSoftBurst: {
        emitters: [{
            emitArea: {x: 0, y: 0, width: 1},
            reserve: 140,
            maxAliveParticles: 180,
            frequency: -1,
            quantity: 112,
            lifespan: {min: 900, max: 1900},
            angle: {min: 0, max: 360},
            speed: {min: 100, max: 260},
            speedX: {min: 0, max: 0},
            speedY: {min: 0, max: 0},
            gravityY: 180,
            scale: {start: 0.55, end: 0.08},
            rotate: {min: -33, max: 33},
            alpha: {start: 0.95, end: 0},
            tint: FIREWORK_SALUTE_COLORS,
        }],
    },
    protonFireworks: {
        cascade: {
            root: {base: "fireworkRocket"},
            onEmit: [
                {
                    id: "rocketTrail",
                    type: "followEmitter",
                    destroyDelayMs: 700,
                    emitter: {base: "fireworkRocketTrail"},
                },
            ],
            onDeath: [
                {
                    id: "denseBurst",
                    type: "explodeEmitter",
                    chance: 0.7,
                    destroyDelayMs: 3600,
                    emitter: {base: "protonFireworksDenseBurst"},
                },
                {
                    id: "softBurst",
                    type: "explodeEmitter",
                    chance: 0.3,
                    destroyDelayMs: 3600,
                    emitter: {base: "protonFireworksSoftBurst"},
                },
            ],
        },
    },
    fountain: {
        emitters: [{
            emitArea: {x: 0, y: 0, width: 1},
            reserve: 140,
            maxAliveParticles: 220,
            frequency: 70,
            quantity: 5,
            lifespan: {min: 1700, max: 2800},
            angle: {min: 250, max: 290},
            speed: {min: 280, max: 560},
            speedX: {min: 0, max: 0},
            speedY: {min: 0, max: 0},
            gravityY: 620,
            scale: {start: 0.5, end: 0.18},
            rotate: {min: 0, max: 720},
            alpha: {start: 1, end: 0},
        }],
    },
    fontaine_double_infinite: {
        emitters: [
            {
                base: "fountain",
                angle: {min: 292, max: 338},
                frequency: 85,
                quantity: 3,
                scale: {start: 0.46, end: 0.22},
                alpha: {start: 1, end: 0.28},
            },
            {
                base: "fountain",
                angle: {min: 202, max: 248},
                frequency: 85,
                quantity: 3,
                scale: {start: 0.46, end: 0.22},
                alpha: {start: 1, end: 0.28},
            },
        ],
    },
    rain: {
        emitters: [{
            emitArea: {x: 0, y: -120, width: DEFAULT_PARTICLE_EFFECT_AREA_WIDTH},
            reserve: 120,
            maxAliveParticles: 180,
            frequency: 75,
            quantity: 2,
            lifespan: {min: 2200, max: 3600},
            speedX: {min: -20, max: 20},
            speedY: {min: 300, max: 520},
            gravityY: 40,
            scale: {start: 0.42, end: 0.42},
            rotate: {min: 0, max: 360},
            alpha: {start: 0.82, end: 0.82},
        }],
    },
    twinkleField: {
        emitters: [{
            emitArea: {x: 0, y: -80, width: DEFAULT_PARTICLE_EFFECT_AREA_WIDTH},
            reserve: 90,
            maxAliveParticles: 140,
            frequency: 130,
            quantity: 2,
            lifespan: {min: 1800, max: 3000},
            speedX: {min: -18, max: 18},
            speedY: {min: 20, max: 75},
            gravityY: 0,
            scale: {start: 0.16, end: 0.62},
            rotate: {min: 0, max: 540},
            alpha: {start: 0, end: 1},
        }],
    },
    bubbleField: {
        emitters: [{
            emitArea: {x: 0, y: 0, width: DEFAULT_PARTICLE_EFFECT_AREA_WIDTH},
            reserve: 70,
            maxAliveParticles: 100,
            frequency: 190,
            quantity: 1,
            lifespan: {min: 3600, max: 6200},
            speedX: {min: -24, max: 24},
            speedY: {min: -20, max: 20},
            gravityY: 0,
            scale: {start: 0.18, end: 0.5},
            rotate: {min: 0, max: 360},
            alpha: {start: 0.12, end: 0.56},
        }],
    },
    trail: {
        emitters: [{
            emitArea: {x: 0, y: 0, width: 1},
            reserve: 80,
            maxAliveParticles: 120,
            frequency: 35,
            quantity: 2,
            lifespan: {min: 650, max: 1200},
            speedX: {min: -80, max: 80},
            speedY: {min: -80, max: 80},
            gravityY: 160,
            scale: {start: 0.36, end: 0.04},
            rotate: {min: 0, max: 540},
            alpha: {start: 0.9, end: 0},
        }],
    },
};
