// ⚠️ This file is auto-generated by assets-config.js. Do not edit manually.
export const autoAssetsConfig = {
  sounds: {},
  fonts: {},
  images: {
    iconCloseCrossWhite: {
      url: "./assets/atlases/klondike_01.png",
      name: "iconCloseCrossWhite",
      frameName: "icon.close_cross.white.png",
      width: 52,
      height: 52,
      fallbackUrls: [
        "./assets/atlases/main.png"
      ]
    },
    phaser3Logo: {
      url: "./assets/images/phaser3-logo.png",
      name: "phaser3Logo"
    },
    red: {
      url: "./assets/images/red.png",
      name: "red"
    },
    space3: {
      url: "./assets/images/space3.png",
      name: "space3"
    },
    uiUsefulBgNine32: {
      url: "./assets/atlases/klondike_01.png",
      name: "uiUsefulBgNine32",
      frameName: "ui.useful.bg.nine.32.png",
      width: 92,
      height: 76,
      fallbackUrls: [
        "./assets/atlases/main.png"
      ]
    }
  },
  preload: {
    sounds: [],
    fonts: [],
    images: [
      {
        name: "phaser3Logo",
        url: "./assets/images/phaser3-logo.png"
      },
      {
        name: "red",
        url: "./assets/images/red.png"
      },
      {
        name: "space3",
        url: "./assets/images/space3.png"
      }
    ],
    atlases: [
      {
        name: "klondike01",
        jsonUrl: "./assets/atlases/klondike_01.json",
        pngUrl: "./assets/atlases/klondike_01.png"
      },
      {
        name: "main",
        jsonUrl: "./assets/atlases/main.json",
        pngUrl: "./assets/atlases/main.png"
      }
    ]
  }
} as const;
