// ⚠️ This file is auto-generated by assets-config.js. Do not edit manually.
export const autoAssetsConfig = {
  sounds: {},
  fonts: {},
  images: {
    iconCloseCrossWhite: {
      url: "./assets/atlases/klondike_01.png",
      name: "iconCloseCrossWhite",
      frameName: "icon.close_cross.white.png",
      width: 52,
      height: 52,
      fallbackUrls: [
        "./assets/atlases/main.png"
      ]
    },
    uiUsefulBgNine32: {
      url: "./assets/atlases/klondike_01.png",
      name: "uiUsefulBgNine32",
      frameName: "ui.useful.bg.nine.32.png",
      width: 92,
      height: 76,
      fallbackUrls: [
        "./assets/atlases/main.png"
      ]
    }
  },
  preload: {
    sounds: [],
    fonts: [],
    images: [],
    atlases: [
      {
        name: "atlases",
        jsonUrl: "./assets/atlases.json",
        pngUrl: "./assets/atlases.png"
      },
      {
        name: "atlases05x",
        jsonUrl: "./assets/atlases@0.5x.json",
        pngUrl: "./assets/atlases@0.5x.png"
      },
      {
        name: "klondike01",
        jsonUrl: "./assets/atlases/klondike_01.json",
        pngUrl: "./assets/atlases/klondike_01.png"
      },
      {
        name: "main",
        jsonUrl: "./assets/atlases/main.json",
        pngUrl: "./assets/atlases/main.png"
      }
    ]
  }
} as const;
